# Change these first
owner: RoblKyogre # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Main Server
    check: "tcp-ping"
    url: craftingcomrades.net
    port: 22
  - name: RoblKyogre Server
    check: "tcp-ping"
    url: roblkyogre.craftingcomrades.net
    port: 22

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.craftingcomrades.net
  # baseUrl: /your-repo-name
  logoUrl: https://status.craftingcomrades.net/icon.png
  favicon: https://status.craftingcomrades.net/icon.png
  name: Crafting Comrades Server Status
  themeUrl: https://status.craftingcomrades.net/comrade.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *" # Accounting for server updates

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
